In [ ]:
'''Question 6: Train a KNN Classifier on the Wine dataset with and without feature
scaling. Compare model accuracy in both cases.
Dataset:
Use the Wine Dataset from sklearn.datasets.load_wine().
(Include your Python code and output in the code box below.)
Answer: '''
from sklearn.datasets import load_wine

In [ ]:
wine = load_wine()
x = wine.data
y = wine.target

In [ ]:
x

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [ ]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test, y_train,y_test = train_test_split(x, y , test_size = 0.3, random_state = 1)

In [ ]:
x_train.shape, x_test.shape

((124, 13), (54, 13))

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
clf = KNeighborsClassifier()
clf

KNeighborsClassifier()

In [ ]:
clf.fit(x_train, y_train)

KNeighborsClassifier()

In [ ]:
y_pred = clf.predict(x_test)
y_pred

array([1, 1, 2, 2, 0, 1, 2, 0, 2, 1, 0, 2, 1, 0, 2, 1, 1, 0, 1, 0, 0, 1,
       2, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 2, 1, 1, 2, 1, 0, 0, 1, 2, 0,
       0, 0, 0, 0, 0, 0, 1, 2, 2, 0])

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print(confusion_matrix(y_test, y_pred))

[[21  0  2]
 [ 2 12  5]
 [ 0  7  5]]


In [ ]:
accuracy_score(y_test, y_pred)

0.7037037037037037

In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.91      0.91      0.91        23
           1       0.63      0.63      0.63        19
           2       0.42      0.42      0.42        12

    accuracy                           0.70        54
   macro avg       0.65      0.65      0.65        54
weighted avg       0.70      0.70      0.70        54



In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler = StandardScaler()

In [ ]:
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [ ]:
knn_scaled = KNeighborsClassifier()
knn_scaled.fit(x_train_scaled, y_train)

KNeighborsClassifier()

In [ ]:
y_pred_scaled = knn_scaled.predict(x_test_scaled)
y_pred_scaled

array([2, 1, 0, 1, 0, 2, 1, 0, 2, 1, 0, 0, 1, 0, 1, 1, 2, 0, 1, 0, 0, 1,
       2, 0, 0, 2, 0, 0, 0, 2, 1, 2, 2, 0, 1, 1, 1, 1, 1, 0, 0, 1, 2, 0,
       0, 0, 1, 0, 0, 0, 1, 2, 2, 0])

In [ ]:
print(confusion_matrix(y_test, y_pred_scaled))

[[23  0  0]
 [ 1 18  0]
 [ 0  0 12]]


In [ ]:
print(accuracy_score(y_test, y_pred_scaled))

0.9814814814814815


In [ ]:
print(classification_report(y_test,y_pred_scaled))

              precision    recall  f1-score   support

           0       0.96      1.00      0.98        23
           1       1.00      0.95      0.97        19
           2       1.00      1.00      1.00        12

    accuracy                           0.98        54
   macro avg       0.99      0.98      0.98        54
weighted avg       0.98      0.98      0.98        54



In [ ]:
print(accuracy_score(y_test, y_pred))
print(accuracy_score(y_test, y_pred_scaled))

0.7037037037037037
0.9814814814814815


In [ ]:
'''Question 7: Train a PCA model on the Wine dataset and print the explained variance
ratio of each principal component.
(Include your Python code and output in the code box below.)
Answer: '''


In [ ]:
from sklearn.datasets import load_wine
data = load_wine()
x = data.data
y = data.target

In [ ]:
x

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [ ]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=1)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)

In [ ]:
from sklearn.decomposition import PCA
pca = PCA()
pca

PCA()

In [ ]:
x_train = pca.fit_transform(x_train)
x_train

array([[-0.95748971, -2.17579819, -0.093707  , ...,  0.81463512,
        -0.11141264,  0.15700912],
       [ 2.55013055,  1.09031172,  1.01814224, ..., -0.15340982,
        -0.19750654, -0.09499433],
       [ 2.32213284,  1.14232714,  1.17906173, ...,  0.28257551,
         0.09325723, -0.15959916],
       ...,
       [-0.43925993, -1.07497032,  0.15546343, ..., -0.20121309,
        -0.14429293,  0.31239456],
       [-2.57691691,  0.14219769,  0.55523068, ...,  0.66832023,
         0.09543304, -0.33293574],
       [ 1.32885281,  0.42594711, -0.19051397, ..., -0.05389311,
        -0.47556324,  0.03418347]])

In [ ]:
x_test = scaler.transform(x_test)
x_test = pca.transform(x_test)
x_test

array([[-2.14192399e+00,  1.09547346e+00, -1.45489282e-01,
        -1.09336402e+00, -1.87417128e-01, -4.28054929e-01,
         7.18649819e-01, -8.22804557e-01, -6.84936670e-02,
         2.95410062e-02, -8.70065922e-02, -1.98718087e-02,
        -4.71340802e-01],
       [ 2.04226303e-01, -1.70047857e+00,  8.61101637e-01,
        -2.36013210e-01,  1.09119837e+00,  2.80278788e-01,
        -1.77493030e-01, -7.44133633e-01, -9.81480725e-02,
         9.37571860e-01,  3.53619242e-02,  7.63218577e-02,
         3.17874912e-01],
       [ 2.20263757e+00,  1.47431605e+00, -1.69426991e-01,
         5.14937175e-01,  1.16023292e+00, -9.63258593e-01,
         5.19207785e-01, -3.42601488e-01, -6.98804308e-01,
        -3.98961579e-01,  7.64853013e-01,  1.91531126e-01,
        -4.85646105e-02],
       [ 2.09927009e+00, -6.35164407e-01, -8.95397276e-01,
        -4.98790457e-01,  4.34341374e+00,  1.94808356e+00,
         8.16899818e-01, -1.12420559e+00,  8.92591176e-01,
         1.13047448e+00, -2.24936865e

In [ ]:
pca.components_

array([[ 0.09041052, -0.25298779, -0.01602653, -0.23041073,  0.08008494,
         0.40226932,  0.43202681, -0.29396827,  0.30712828, -0.14263937,
         0.32126087,  0.39611073,  0.24164525],
       [ 0.47673487,  0.17699549,  0.3238999 , -0.02707893,  0.38435766,
         0.0878164 ,  0.02713712,  0.01053185,  0.07541547,  0.48287748,
        -0.2547302 , -0.11157837,  0.40406288],
       [-0.23238477,  0.14068315,  0.58906416,  0.6268684 ,  0.16065207,
         0.1370189 ,  0.12736772,  0.09888055,  0.18264994, -0.15871686,
         0.06303092,  0.15071199, -0.17442128],
       [ 0.00653254,  0.5915821 , -0.29652032,  0.04753301, -0.24327871,
         0.14810192,  0.11529495, -0.26650234,  0.4165868 ,  0.06333815,
        -0.4026246 ,  0.11710444, -0.20246685],
       [-0.29432656,  0.0014267 , -0.11985095, -0.005842  ,  0.66735506,
        -0.21703103, -0.10212866, -0.59602859, -0.0638698 , -0.13199357,
        -0.11601912, -0.0628391 , -0.04376107],
       [-0.34363734, -0.252437

In [ ]:
x_train.shape

(124, 13)

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=1)

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=1)
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
pca = PCA(n_components=3)
x_train = pca.fit_transform(x_train)
x_train

array([[ 2.69187561, -1.79953625, -2.03965086],
       [-0.07701951, -0.741078  ,  0.45791988],
       [ 1.93069606,  2.13355055,  0.73247345],
       [-2.84619701,  1.08346274, -1.03990261],
       [-0.04782523, -2.7862018 ,  0.85672396],
       [-2.95160086, -0.55179529, -0.74696624],
       [ 3.61977385,  1.51773583, -1.45858691],
       [ 0.08089566, -2.22881184, -0.43927332],
       [ 1.20762232,  2.11176347, -0.08004563],
       [ 1.20726215, -2.1871067 ,  0.22867444],
       [ 1.51608339,  1.08617348,  0.43658146],
       [-3.49280489,  0.24710539, -1.36850077],
       [-2.43444765,  2.41084634,  0.43463154],
       [-2.16905093,  1.95128582,  0.75604027],
       [-2.72128853,  2.65983629, -0.89848791],
       [-2.02800641, -1.67124881, -1.88898073],
       [-0.44579785, -2.42336053, -1.32616244],
       [ 1.31081975,  0.5394422 ,  0.91666027],
       [-3.27890767,  1.75630367, -0.46627453],
       [ 2.67569329,  1.51333599,  0.8664067 ],
       [-1.30779432, -0.77069655, -0.467

In [ ]:
pca.n_components

3

In [ ]:
pca.components_

array([[ 0.09033778, -0.2617015 , -0.02861725, -0.23902998,  0.05937214,
         0.40016121,  0.43068384, -0.2906271 ,  0.30764148, -0.13677013,
         0.32164466,  0.39504728,  0.24274147],
       [ 0.46267695,  0.1835847 ,  0.32830515, -0.02564564,  0.4118872 ,
         0.0910284 ,  0.03648962,  0.00481246,  0.0912468 ,  0.47394405,
        -0.25869834, -0.10364941,  0.39227014],
       [-0.24559541,  0.07830254,  0.60430422,  0.61254748,  0.17080957,
         0.13842811,  0.13090752,  0.13648326,  0.14618871, -0.16703385,
         0.10914569,  0.15099078, -0.15833021]])

In [ ]:
pca.explained_variance_ratio_

array([0.35383437, 0.20465595, 0.11223578])

In [ ]:
'''Question 8: Train a KNN Classifier on the PCA-transformed dataset (retain top 2
components). Compare the accuracy with the original dataset.
(Include your Python code and output in the code box below.)
Answer: '''


In [2]:

from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

wine = load_wine()
X = wine.data
y = wine.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

knn_original = KNeighborsClassifier(n_neighbors=5)
knn_original.fit(X_train_scaled, y_train)
y_pred_original = knn_original.predict(X_test_scaled)
accuracy_original = accuracy_score(y_test, y_pred_original)

pca = PCA(n_components=2)
X_train_pca = pca.fit_transform(X_train_scaled)
X_test_pca = pca.transform(X_test_scaled)

knn_pca = KNeighborsClassifier(n_neighbors=5)
knn_pca.fit(X_train_pca, y_train)
y_pred_pca = knn_pca.predict(X_test_pca)
accuracy_pca = accuracy_score(y_test, y_pred_pca)

print("Accuracy on original dataset:", accuracy_original)
print("Accuracy on PCA-transformed dataset (2 components):", accuracy_pca)


Accuracy on original dataset: 0.9629629629629629
Accuracy on PCA-transformed dataset (2 components): 0.9814814814814815


In [ ]:
''''Question 9: Train a KNN Classifier with different distance metrics (euclidean,
manhattan) on the scaled Wine dataset and compare the results.
(Include your Python code and output in the code box below.)
Answer: '''


In [ ]:

wine = load_wine()
X = wine.data
y = wine.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


knn_euclidean = KNeighborsClassifier(n_neighbors=5, metric='euclidean')
knn_euclidean.fit(X_train_scaled, y_train)

y_pred_euclidean = knn_euclidean.predict(X_test_scaled)
accuracy_euclidean = accuracy_score(y_test, y_pred_euclidean)

knn_manhattan = KNeighborsClassifier(n_neighbors=5, metric='manhattan')
knn_manhattan.fit(X_train_scaled, y_train)

y_pred_manhattan = knn_manhattan.predict(X_test_scaled)
accuracy_manhattan = accuracy_score(y_test, y_pred_manhattan)

print("Accuracy with Euclidean distance:", accuracy_euclidean)
print("Accuracy with Manhattan distance:", accuracy_manhattan)


Accuracy with Euclidean distance: 0.9629629629629629
Accuracy with Manhattan distance: 0.9629629629629629


In [ ]:
'''Question 10: You are working with a high-dimensional gene expression dataset to
classify patients with different types of cancer.
Due to the large number of features and a small number of samples, traditional models
overfit.
Explain how you would:
● Use PCA to reduce dimensionality
● Decide how many components to keep
● Use KNN for classification post-dimensionality reduction
● Evaluate the model
● Justify this pipeline to your stakeholders as a robust solution for real-world
biomedical data
(Include your Python code and output in the code box below.)
Answer: '''


In [ ]:

import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

np.random.seed(42)
X = np.random.rand(100, 5000)
y = np.random.randint(0, 3, 100)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

pca = PCA(n_components=0.95)
X_train_pca = pca.fit_transform(X_train_scaled)
X_test_pca = pca.transform(X_test_scaled)

print("Original number of features:", X.shape[1])
print("Reduced number of components:", X_train_pca.shape[1])

knn = KNeighborsClassifier(n_neighbors=5)

cv_scores = cross_val_score(knn, X_train_pca, y_train, cv=5)

knn.fit(X_train_pca, y_train)
y_pred = knn.predict(X_test_pca)
test_accuracy = accuracy_score(y_test, y_pred)

print("Cross-validation accuracy:", cv_scores.mean())
print("Test accuracy:", test_accuracy)
